### ISSUE TITLE
Game freezes when trying to link certain storages

### ISSUE THREAD

**Issue by Cheremenin** [bbradson/Performance-Fish#47] opened 2024-05-05 22:19 UTC
When linking together some things like hoppers (but not the vanilla or VE shelves, or Adaptive Storage Framework buildings) the game will completely freeze

Seems to be connected to Performance Fish

http://0x0.st/XX7c.log

**Comment by tiger8255** [comment] 2024-05-06 02:44
I get the same issue with the vanilla shelves

**Comment by Cheremenin** [comment] 2024-05-06 05:50
> I get the same issue with the vanilla shelves
> 
> Seems like you can toggle all patches off when you link containers as a temporary workaround? Not sure which patch it is that's causing the issue.

Judging by some other reports it looks like it's the "TryFindBestBetterStoreCellForWorker" patch doing it

**Comment by tiger8255** [comment] 2024-05-06 14:40
> > I get the same issue with the vanilla shelves
> > Seems like you can toggle all patches off when you link containers as a temporary workaround? Not sure which patch it is that's causing the issue.
> 
> Judging by some other reports it looks like it's the "TryFindBestBetterStoreCellForWorker" patch doing it

I actually tried turning that off by itself and still froze. I don't think that's the one causing it when linking storages.

**Comment by TheHitman2772** [comment] 2024-05-06 21:14
I had to turn off all patches in that section to stop the crashes, but I think the one TryFindBestBetterStoreCellForWorker patch can be disabled by itself for vanilla. Mods that mess with storage seem to require turning off all the other prepatches in that section of optimizations.

**Comment by sunxyw** [comment] 2024-05-07 07:02
You have to disable "TryFindBestBetterStoreCellForWorker" patch, and all others patches that relies on it.

Patches to disable:
- StorageSettingsPatches
  - AllowedToAccept
- StoreUtilityPrepatches
  - TryFindBestBetterStoreCellFor
  - TryFindBestBetterStoreCellForWorker
- Improve hauling accuracy

Restart your game to make the changes apply.

Also, duplicate of #44

**Comment by quicksilverfox** [comment] 2024-05-10 03:30
> You have to disable "TryFindBestBetterStoreCellForWorker" patch, and all others patches that relies on it.

I did that, and not only it fixed crashes, but also serious lag spikes I had.

**Comment by kvalek** [comment] 2024-05-13 13:21
I can confirm that this happens to my game aswell. Game will freeze if i try to link 7 or more shelves at the same time. 6 works fine. This was all vanilla shelves.
Only storage mod i have is Rimfridge. Will try to disable the patch.

**Comment by Izeick** [comment] 2024-05-20 22:27
+1

**Comment by VaelophisNyx** [comment] 2024-05-21 20:34
Getting this myself, also tried the listed patches to turn off, still froze.

**Comment by FWDekker** [comment] 2024-05-21 21:03
@VaelophisNyx I also encountered this bug just now, but for me sunxyw's solution worked fine. Did you restart the game after disabling the patches? I guess it might also help to clear the cache (which you can do at the bottom of the mod's settings). Otherwise, your bug might be different from the one others are encountering.

**Comment by VaelophisNyx** [comment] 2024-05-21 21:34
> @VaelophisNyx I also encountered this bug just now, but for me sunxyw's solution worked fine. Did you restart the game after disabling the patches? I guess it might also help to clear the cache (which you can do at the bottom of the mod's settings). Otherwise, your bug might be different from the one others are encountering.

a reload after the settings changed fixed the issue.

**Comment by SirMalFet** [comment] 2024-06-01 14:11
Can confirm this happens when linking 7+ storages.

**Comment by Foxtr0t1337** [comment] 2024-06-15 19:26
Found the problem in the source code.
It is a infinite loop caused by decreasing an index by a unchecked negative number.
Will post a pr in a moment.

And no, in my case it is not because of TryFindBestBetterStoreCellForWorker but TryFindBestBetterStoreCellFor.
When I link shelves it freezes.

**Comment by Foxtr0t1337** [comment] 2024-06-15 20:17
PR is made, please feel free to try the fix out.
If it can't fix the problem please let me know.
If it can fix it, that's great, please let me know. ; )

To apply the fix you will need to pull the commit to your local mod folder and compile it.
Or replace the 1.5/1.4 folder of the mod with ones in my repo which have the fix compiled.

**Comment by sunxyw** [comment] 2024-06-16 08:36
> PR is made, please feel free to try the fix out. If it can't fix the problem please let me know. If it can fix it, that's great, please let me know. ; )
> 
> To apply the fix you will need to pull the commit to your local mod folder and compile it. Or replace the 1.5/1.4 folder of the mod with ones in my repo which have the fix compiled.

Hi Foxtr0t1337, I just downloaded the dll you compiled to try it out and it did fix the problem caused when linking storage shelves, thank you very much!

**Comment by Jigain** [comment] 2024-06-16 09:37
> PR is made, please feel free to try the fix out. If it can't fix the problem please let me know. If it can fix it, that's great, please let me know. ; )
> 
> To apply the fix you will need to pull the commit to your local mod folder and compile it. Or replace the 1.5/1.4 folder of the mod with ones in my repo which have the fix compiled.

Can also confirm, after replacing my 1.5 folder with the one from your repo, no further crashes.

**Comment by bbradson** [comment] 2024-06-16 22:26
The fix is merged in now

**Closed by bbradson** 2024-06-16 22:26 UTC
