### ISSUE TITLE
Unable to do bill when the WorkGiver_DoBillOptimization::TryFindBestIngredientsHelper_InnerDelegate setting is enabled.

### ISSUE THREAD

**Issue by basicsmods** [bbradson/Performance-Fish#3] opened 2022-11-27 09:38 UTC
Nothing gets printed to my log file, but with this setting on, I'm currently unable to do a bill (it says the ingredients are missing). As soon as I toggle the setting off, I'm able to do that bill. (The bill is crafting High-Explosive Shells.) There are no zoning issues (I tried with the pawn on the unrestricted zone to make sure).

First screenshot is what the context menu looks like with the setting OFF. Second is with the setting ON. Third is showing the setting OFF. 
![image](https://user-images.githubusercontent.com/108436227/204128189-346b51e6-c667-4497-9b7f-fa9ff7650f16.png)

![image](https://user-images.githubusercontent.com/108436227/204128220-4d3a3a89-8091-4f0e-9777-1443b967fb50.png)

![image](https://user-images.githubusercontent.com/108436227/204128224-2c9814ed-6874-47b8-b2cb-ea3cb3a14dff.png)

I'm uploading the save file that this is currently happening on if you want to see if you can reproduce locally. I have a bunch of other mods associated with that save, but I just tested loading it with ONLY Performance Fish enabled and the issue is still present. So hopefully you'd be able to load into that save with only Performance Fish and see it for yourself. Just select Ben and right click the Machining Table. (Toggle the setting above on and off to see the difference.)

[Squirrel Gang (4).zip](https://github.com/bbradson/Performance-Fish/files/10097939/Squirrel.Gang.4.zip)

**Comment by LocoPineapples** [comment] 2023-01-11 00:17
I'm gonna bump this, I've been having the exact same issue as well. With InnerDelegate on, my pawns are unable to craft anything as it doesn't register any materials available. OP explained everything much better than I could've, so I'll just post my Hugslib log here and hope it helps to some degree.

https://gist.github.com/809d477f938e2ceef3a7f98e3826ff4e

**Comment by BlackMoons** [comment] 2023-02-04 00:41
Can confirm getting same bug while trying to install a bionic leg.

**Comment by alreShan** [comment] 2023-02-04 06:38
exactly same for me too

**Comment by alreShan** [comment] 2023-02-04 22:27
although pawns will find material and do the bill theirselves.

**Comment by DAOWAce** [comment] 2023-03-21 18:02
Been wondering why it kept saying it was missing surgery objects.. remembered this issue, disabled "NoMixHelper" and the issue stopped.

I guess I'll just outright disable the InnerDelegate too; don't want to run into other bills breaking, though I hadn't noticed any problems with them yet, just operations.

**Comment by Mario90900** [comment] 2023-03-24 01:47
I was getting this same issue trying to craft guns, and using the Dragon Altar from Dragon's Decent, and I am glad to have found this issue post as well. Not sure if it has to do with using a lot of storage areas cause of Deep Storage, but I also had no issue with the pawns actually doing the tasks themselves - Just forcing them to do it gave that same error of lacking materials. It didn't seem to appear until later in my save, and I didn't change the modlist too much either. Perhaps it just has a portion that only has trouble with bigger colonies and lots of storage areas? I also believe my map has a Real Ruin with spawned Steel in a storage trapped somewhere, as according to the resource loadout, I have a lot more then I really have access to.

If it helps any to find the cause of any conflicts, I can also share my modlist. But hopefully this might be of any help!

**Comment by angrycannibal** [comment] 2023-05-19 19:33
Also having this issue, just installed PF yesterday. I was able to manually command surgery jobs with PF initially, but all of the sudden I started having issues, it was showing I was missing parts on some surgery jobs, then any surgery job was showing I was missing parts. For example I was able to command a pawn to install a right leg, but I couldn't force them to install a left leg, but I was able to install legs on other pawns, then any forced surgery job stopped working. Also if I used dev mode to add more materials it didn't help. 

Then I found that I couldn't force pawns to make certain bills on work benches, it was showing the materials were missing, like shred mechanoids despite having a pile of them next to the work bench. I could force them to craft components, but I could force them to make bionics or craft clothes. Pawns were able to perform all of these jobs on their own but I couldn't force them to do it. 

Thankfully disabling TryFindBestIngredientsHelper_InnerDeligate seems to have fixed this issue. 

I did a quick dev mode test without any mods except P Fish and Harmony, with TryFindBestIngredientsHelper_InnerDeligate enabled, I was able to force pawns to perform the same jobs I wasn't able to previously. So there is most likely a compatibility issue 

I've attached a list of the mods I am using. 

[Mod List with P Fish.txt](https://github.com/bbradson/Performance-Fish/files/11519629/Mod.List.with.P.Fish.txt)

**Comment by quicksilverfox** [comment] 2023-05-27 08:05
Can confirm the issue.

**Comment by bbradson** [comment] 2023-05-28 02:27
This is a known bug and really doesn't need more confirmation. It'll get fixed with the next update, but the workaround being to simply toggle off one setting keeps it from being much of a priority. Toggling off TryFindBestIngredientsInSet_NoMixHelper instead of InnerDelegate works too and doesn't even come with most of the performance hit

**Comment by bbradson** [comment] 2023-06-03 18:26
The new build should have this fixed now

**Closed by bbradson** 2023-06-03 18:26 UTC
